### PR TITLE
Add unlisted interfaces

### PR DESCRIPTION
**Pull request by whackyhack**
modified:   install.sh

For issue #33

### CODE REVIEW

**Comment by wiedehopf** [comment]
That's problematic because of docker and other bridge interfaces.
Also each time the install script is run you add new entries into the configuration.

**Comment by whackyhack** [comment]
The `() && continue` check prevents repetitive entries, if that's what you mean by new entries.  Admittedly I haven't handled docker.  I don't quite know how collectd or even systemd work under docker.  Do you mean that all bridges would be exposed in every docker via /sys/class/net, thus the unfortunate graphs1090 will end up aggregating traffic from every docker running on the host?

**Comment by wiedehopf** [comment]
Run the install script twice .... then look at collectd.conf.
It'll have duplicate entries, you'd have to check if the entry already exists.

And i have a bridge device from zerotier and a docker device from playing with docker on my system.
Those would be chosen to be displayed.
That's bad.
I'd rather have some rare systems have missing graphs than many more having the wrong graphs.

You could restrict the devices used so they start with enp and wlp, i believe some systems do eno
That way ... more chance of only catching the devices we want.


Then honestly i'd restrict this code to work on the first install only.
I try not to touch the collectd.conf too much after that. (yes some minor changes but not too much.)
People who can't put their network devices in that file ... i don't care that much about them.
If they can't get the graphs to work .... i'd much prefer that to people having useless graphs labeled ethernet and wireless.

**Comment by whackyhack** [comment]
I see that problems arise in docker's host; this can also happen if a host runs virtualization like libvirt/qemu.  I added exclusions for these common mechanisms.

Repetitive entries were caused by bad quotes that wasn't in my prototype.  When I tried to collapse exclusion and existence check onto one line (which itself is a dumb idea in hindsight), the quotes got mixed up.  Fixed.

**Pull request merged**
