### PR TITLE
Use /tmp instead of /run for image files

### PR DESCRIPTION
**Pull request by mikaey**
Hey hey!

So here's my issue.  I'm not sure if this is the _right_ way to solve this, but it is _a_ way to solve it.

I'm running dump1090-fa/tar1090/graphs1090 on an Orange Pi Zero running Armbian.  `systemd` creates a 24M ramdisk at startup for `/run`.  On top of that, `systemctl` will refuse to restart services if `/run` has less than 16M of free space -- which can cause problems if you're trying to run an `apt upgrade`.

On my system, non-graphs1090 related services are using about 6M of space, with graphs1090 using about another 5M of space.  This brings `/run` down to 13M of free space -- below the threshold where `systemctl` complains about lack of free space.

This change moves the image files over to `/tmp` instead of `/run`.  That way a setup where `/tmp` is using `tmpfs` will still avoid writing images to the SD card, while a setup where `/tmp` is disk-based will write the images to disk.

### CODE REVIEW

**Comment by wiedehopf** [comment]
Look into fixing your system.

This is not normally an issue and i don't want the images to be written to the disk by default.

**Comment by wiedehopf** [comment]
Edit `/etc/fstab`

add this line (or modify an existing entry for /run)
```
tmpfs /run tmpfs rw,nosuid,nodev,mode=755,size=500M

```
```
sudo mount -o remount /run
```

**Comment by mikaey** [comment]
Erm...you realize that an Orange Pi Zero only has 256MB of RAM, and you want me to create a 500MB ramdisk?

C'mon man...you're breaking systems this way.  You need to give some more fine grained control over where those images get stored.

**Comment by wiedehopf** [comment]
```
du -sh /run/graphs1090 
8.8M	/run/graphs1090
```

So make it an appropriate size for your system.

**Comment by wiedehopf** [comment]
Systems with that little memory are very rare.

With your PR you make the very common case much worse by writing to the sd-card by default.
That's not a PR i will take.
Making it configurable is painful, so i won't do that either.

You've fixed it and you are the first one to have this issue.
Anyhow running collectd with that little memory available is already questionable.
In other words: won't fix.

**Pull request closed without merging**
